#ifndef MPI_PORT_CONSTANT_H_INCLUDE

#define MPI_PORT_CONSTANT_H_INCLUDE

#define MSG_HPGC_FRAMEWORK_RIGHT 0
#define MSG_HPGC_FRAMEWORK_WRONG 1
#define MSG_HPGC_FRAMEWORK_EXIT 2
#define MSG_HPGC_FRAMEWORK_DATA 3

#endif